twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    form_themes: ['bootstrap_4_layout.html.twig']
#    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
#    form_themes: ['bootstrap_3_horizontal_layout.html.twig']

knp_paginator:
    page_range: 6                       # number of links showed in the pagination menu (e.g: you have 10 pages, a page_range of 3, on the 5th page you'll see links to page 4, 5, 6)
    default_options:
        page_name: page                 # page query parameter name
        sort_field_name: sort           # sort field query parameter name
        sort_direction_name: direction  # sort direction query parameter name
        distinct: true                  # ensure distinct results, useful when ORM queries are using GROUP BY statements
        filter_field_name: filterField  # filter field query parameter name
        filter_value_name: filterValue  # filter value query paameter name
    template:

#        pagination:   '@KnpPaginator/Pagination/sliding.html.twig'
        pagination:   '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
#        pagination:   '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'


#        pagination:   '@KnpPaginator/Pagination/twitter_bootstrap_pagination.html.twig'
#        pagination:   '@KnpPaginator/Pagination/foundation_v5_pagination.html.twig'
#        pagination:   '@KnpPaginator/Pagination/bulma_pagination.html.twig'
#        pagination:   '@KnpPaginator/Pagination/semantic_ui_pagination.html.twig'
#        pagination:   '@KnpPaginator/Pagination/materialize_pagination.html.twig'
#        pagination:   '@KnpPaginator/Pagination/tailwindcss_pagination.html.twig'

        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  # filters template